version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: local-dynamodb
    volumes:
      - ./data/local-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

  redis:
    image: redis
    container_name: local-redis
    volumes:
      - ./data/local-redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379